site_name: keeplog
site_description: Terminal session logger with full-text search
site_url: https://rathinadev.github.io/keeplog/
repo_url: https://github.com/rathinadev/keeplog

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.svg
  favicon: assets/favicon.png
  palette:
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - announce.dismiss


extra_css:
  - stylesheets/extra.css

extra:
  generator: false

copyright: Built by rathinadevan

nav:
  - Home: index.md
  - Usage: usage.md
  - Commands: commands.md
  - Configuration: config.md
  - Development: development.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
